name: Create Sprint Branch

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger of the workflow

permissions:
  contents: write  # Ensure the workflow has write permissions

jobs:
  create_sprint_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run sprint calculation script
      id: calc_sprint
      run: python scripts/calculate_sprint_details.py
      env:
        GITHUB_ENV: $GITHUB_ENV

    - name: Set branch name
      run: echo "BRANCH_NAME=$(cat $GITHUB_ENV | grep 'BRANCH_NAME' | cut -d '=' -f2)" >> $GITHUB_ENV

    - name: Checkout master branch and create sprint branch
      if: ${{ env.BRANCH_NAME }} != 'skip'
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        BRANCH_NAME: ${{ env.BRANCH_NAME }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git fetch origin
        git checkout master
        git checkout -b $BRANCH_NAME
        git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} $BRANCH_NAME

    - name: Test if branch is created
      if: ${{ env.BRANCH_NAME }} != 'skip'
      run: |
        git ls-remote --heads origin $BRANCH_NAME
